development:
  adapter: postgresql
  encoding: unicode
  database: provas_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: provas_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: provas_production
  username: provas
  password: 72139118
  host: localhost
  port: 5432
